export const APP_LOAD = 'APP_LOAD'
export const REDIRECT = 'REDIRECT'
export const SET_ = 'SET_'
export const CHANGE_TAB = 'CHANGE_TAB'


export const UPLOADER_UNLOADED = 'UPLOADER_UNLOADED'
export const UPLOADER_LOADED = 'UPLOADER_LOADED'
export const UPDATE_UPLOADS = 'UPDATE_UPLOADS'
export const DELETE_UPLOADS = 'DELETE_UPLOADS'
export const POST_SUBMITTED = 'POST_SUBMITTED'
export const POST_UNFAVORITED = 'POST_UNFAVORITED'
export const POST_LOADED = 'POST_LOADED'
export const POST_UNLOADED = 'POST_UNLOADED'
export const POST_FAVORITED = 'POST_FAVORITED'
export const DELETE_POST = 'DELETE_POST'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const LOGIN_UNLOADED = 'LOGIN_UNLOADED'
export const REGISTER_UNLOADED = 'REGISTER_UNLOADED'

export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const ADD_MEDIUM = 'ADD_MEDIUM'
export const REMOVE_MEDIUM = 'REMOVE_MEDIUM'
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const UPDATE_CHECKBOX = 'UPDATE_CHECKBOX'
export const EDITOR_LOADED = 'EDITOR_LOADED'
export const EDITOR_UNLOADED = 'EDITOR_UNLOADED'

export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER'

export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'

export const PHOTOS_FETCHED = 'PHOTOS_FETCHED'
export const PHOTOS_LOADED = 'PHOTOS_LOADED'
export const PHOTOS_UNLOADED = 'PHOTOS_UNLOADED'

export const PHOTO_LOADED = 'PHOTO_LOADED'
export const PHOTO_UNLOADED = 'PHOTO_UNLOADED'

export const PHOTOS_SUBMITTED = 'PHOTOS_SUBMITTED'

export const PHOTOS_UPLOADED = 'PHOTOS_UPLOADED'
export const PHOTOS_UPLOADING = 'PHOTOS_UPLOADING'

export const UPDATE_UPLOADED_PHOTO = 'UPDATE_UPLOADED_PHOTO'
export const DELETE_UPLOADED_PHOTO = 'DELETE_UPLOADED_PHOTO'

export const UPLOADER_FORM_UNLOADED = 'UPLOADER_FORM_UNLOADED'
export const UPLOAD_PREVIEW_LOADED = 'UPLOAD_PREVIEW_LOADED'
export const DROPZONE_LOADED = 'DROPZONE_LOADED'
export const DROPZONE_UNLOADED = 'DROPZONE_UNLOADED'

export const DELETE_USER = 'DELETE_USER'

export const SETTINGS_UNLOADED = 'SETTINGS_UNLOADED'

export const HOME_LOADED = 'HOME_LOADED'
export const HOME_UNLOADED = 'HOME_UNLOADED'

export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const MODAL_LOADED = 'MODAL_LOADED'
export const MODAL_REDIRECTED = 'MODAL_REDIRECTED'
export const MODAL_UNLOADED = 'MODAL_UNLOADED'




export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'

export const PROFILE_LOADED = 'PROFILE_LOADED'
export const PROFILE_UNLOADED = 'PROFILE_UNLOADED'
export const PROFILE_FAVORITES_UNLOADED = 'PROFILE_FAVORITES_UNLOADED'
export const PROFILE_FAVORITES_LOADED = 'PROFILE_FAVORITES_LOADED'

export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR'
export const SETTINGS_SAVED = 'SETTINGS_SAVED'