export const APP_LOAD = 'APP_LOAD'
export const REDIRECT = 'REDIRECT'
export const SET_PAGE = 'SET_PAGE'
export const CHANGE_TAB = 'CHANGE_TAB'


export const POST_SUBMITTED = 'POST_SUBMITTED'
export const POST_UNFAVORITED = 'POST_UNFAVORITED'
export const POST_PAGE_LOADED = 'POST_PAGE_LOADED'
export const POST_PAGE_UNLOADED = 'POST_PAGE_UNLOADED'
export const POST_FAVORITED = 'POST_FAVORITED'
export const DELETE_POST = 'DELETE_POST'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED'

export const ADD_TAG = 'ADD_TAG'
export const REMOVE_TAG = 'REMOVE_TAG'
export const ADD_MEDIUM = 'ADD_MEDIUM'
export const REMOVE_MEDIUM = 'REMOVE_MEDIUM'
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED'
export const UPDATE_CHECKED_EDITOR = 'UPDATE_CHECKED_EDITOR'
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED'

export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER'

export const ASYNC_START = 'ASYNC_START'
export const ASYNC_END = 'ASYNC_END'

export const PHOTOS_FETCHED = 'PHOTOS_FETCHED'
export const PHOTOS_PAGE_LOADED = 'PHOTOS_PAGE_LOADED'
export const PHOTOS_PAGE_UNLOADED = 'PHOTOS_PAGE_UNLOADED'

export const PHOTO_PAGE_LOADED = 'PHOTO_PAGE_LOADED'
export const PHOTO_PAGE_UNLOADED = 'PHOTO_PAGE_UNLOADED'

export const PHOTOS_SUBMITTED = 'PHOTOS_SUBMITTED'

export const PHOTOS_UPLOADED = 'PHOTOS_UPLOADED'
export const PHOTOS_UPLOADING = 'PHOTOS_UPLOADING'

export const UPDATE_UPLOADED_PHOTO = 'UPDATE_UPLOADED_PHOTO'
export const DELETE_UPLOADED_PHOTO = 'DELETE_UPLOADED_PHOTO'

export const UPLOADER_FORM_UNLOADED = 'UPLOADER_FORM_UNLOADED'
export const UPLOAD_PREVIEW_LOADED = 'UPLOAD_PREVIEW_LOADED'
export const UPLOADER_PAGE_LOADED = 'UPLOADER_PAGE_LOADED'
export const UPLOADER_PAGE_UNLOADED = 'UPLOADER_PAGE_UNLOADED'

export const DELETE_USER = 'DELETE_USER'

export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED'

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED'

export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const MODAL_PAGE_LOADED = 'MODAL_PAGE_LOADED'
export const MODAL_PAGE_REDIRECTED = 'MODAL_PAGE_REDIRECTED'
export const MODAL_PAGE_UNLOADED = 'MODAL_PAGE_UNLOADED'




export const FOLLOW_USER = 'FOLLOW_USER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED'
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED'
export const PROFILE_FAVORITES_PAGE_UNLOADED = 'PROFILE_FAVORITES_PAGE_UNLOADED'
export const PROFILE_FAVORITES_PAGE_LOADED = 'PROFILE_FAVORITES_PAGE_LOADED'

export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR'
export const SETTINGS_SAVED = 'SETTINGS_SAVED'